//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTable.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees_Disciplines
    {
        public int Employees_DisciplinesId { get; set; }
        public int DisciplineId { get; set; }
        public int EmployeeId { get; set; }
    
        public virtual Disciplines Disciplines { get; set; }
        public virtual Employees Employees { get; set; }
    }
}
