//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTable.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specialities
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Specialities()
        {
            this.StudyPlan_Disciplines = new HashSet<StudyPlan_Disciplines>();
        }
    
        public int SpecialityId { get; set; }
        public Nullable<int> SpecialityNumber { get; set; }
        public string SpecialityInfo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudyPlan_Disciplines> StudyPlan_Disciplines { get; set; }
    }
}
