//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTable.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudyPlan_DisciplinesByWeek
    {
        public int StudyPlan_DisciplinesByWeekId { get; set; }
        public int StudyPlan_DisciplinesId { get; set; }
        public Nullable<int> DisciplineId { get; set; }
        public Nullable<int> TotalNumberOfHours { get; set; }
        public Nullable<int> StudyPlanId { get; set; }
        public Nullable<int> HoursOfLectures { get; set; }
        public Nullable<int> HoursOfLaboratory { get; set; }
        public Nullable<int> HoursOfLaboratoryWithComputers { get; set; }
        public Nullable<System.DateTime> MondayOfWeek { get; set; }
    
        public virtual StudyPlan_Disciplines StudyPlan_Disciplines { get; set; }
    }
}
