//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTable.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudyPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudyPlan()
        {
            this.StudyPlan_Disciplines = new HashSet<StudyPlan_Disciplines>();
        }
    
        public int StudyPlanId { get; set; }
        public int GroupId { get; set; }
        public int SpecialityId { get; set; }
        public int SemesterNumber { get; set; }
        public bool IsIndividual { get; set; }
        public Nullable<int> Course { get; set; }
    
        public virtual Groups Groups { get; set; }
        public virtual Specialities Specialities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudyPlan_Disciplines> StudyPlan_Disciplines { get; set; }
    }
}
