//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTable.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudyPlan_Disciplines
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudyPlan_Disciplines()
        {
            this.StudyPlan_DisciplinesByWeek = new HashSet<StudyPlan_DisciplinesByWeek>();
        }
    
        public int StudyPlan_DisciplinesId { get; set; }
        public int StudyPlanId { get; set; }
        public int DisciplineId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> TotalNumberOfHours { get; set; }
        public Nullable<int> HoursOfLectures { get; set; }
        public Nullable<int> HoursOfLaboratory { get; set; }
        public Nullable<int> HoursOfLaboratoryWithComputers { get; set; }
        public Nullable<int> RequiredNumberOfHours { get; set; }
    
        public virtual Disciplines Disciplines { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual StudyPlan StudyPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudyPlan_DisciplinesByWeek> StudyPlan_DisciplinesByWeek { get; set; }
    }
}
