//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTable
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudyPlan_Disciplines
    {
        public int StudyPlan_DisciplinesId { get; set; }
        public int StudyPlanId { get; set; }
        public int DisciplineId { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> TotalNumberOfHours { get; set; }
        public Nullable<int> HoursOfLectures { get; set; }
        public Nullable<int> HoursOfLaboratory { get; set; }
        public Nullable<int> HoursOfLaboratoryWithComputers { get; set; }
        public Nullable<int> RequiredNumberOfHours { get; set; }
    
        public virtual Disciplines Disciplines { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual StudyPlan StudyPlan { get; set; }
    }
}
